name: azmonrahnamayi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: any
  shared_preferences: any
  share_plus: any
  google_fonts: any
  url_launcher: any
  confetti: any
  intl: ^0.20.2
  image_picker: ^1.0.4
  universal_io: ^2.0.4
  file_picker: ^5.2.1
  percent_indicator: ^4.2.3
  uuid: ^3.0.7
  path_provider: ^2.0.15
  path: ^1.8.3
  image: ^4.0.17

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/questions/
    - assets/images/
    - assets/images/list1/
    - assets/images/list2/
    - assets/images/list3/
    - assets/images/list4/
    - assets/images/list5/
    - assets/images/list6/
    - assets/images/list7/
    - assets/images/list8/
    - assets/images/list9/
    - assets/images/list10/
    - assets/images/avatar.png
    - assets/images/logo.png
    - assets/images/nexzo.png
